### PR TITLE
Rhombus

### PR DESCRIPTION
**Pull request by ghost**
In primary school, one of the first figures that children can study is, with the square and rectangle, the rhombus.

Generally, the definition is multiple. See: https://en.wikipedia.org/wiki/Rhombus

In this file, the definitions introduced in the GeoCoq quadrilaterals.v file are used.  

- The existence of the construction of "Plg" is shown.

- The existence of a rhombus is shown. 

Both constructions are valid in absolute geometry.

- The uniqueness of a rhombus constructed from 3 given points is shown.

TODO:

- In Euclidean geometry, construction of a rhombus from 3 determined points.

- What about rhombus in non-euclidean geometry case ?

### CODE REVIEW

**Comment by jnarboux** [comment]
Dear Roland.

Thanks a lot for the contribution. We can not include it yet because there are open sections, so the file does not compile (see the travis logs). You need to close the section Rhombus_Existence_Unicity at the end of the file.

It would be also better to move the additional lemmas about Plg out of the Rhombus file.
We have everything in a quadrilateral file, but I may be worth spliting this file in differents parts.
Charly  is working on the generalization of some of Tarski's chapters to geometry of arbitrary dimension. You may also consider removing the 2D assumption in your proofs when it is possible. Our definition of Rhombus implies that it is a 2D figure, because the diagonals intersect, but we could have some charecterizations for which we need to assume it is 2D, for example that the four sides are congruent.

For the existence of parallelograms, you already have the lemma:
plg_existence
I understand you did not find it, because we have two equivalent definitions of parallelogram in the library.... it should be merged to keep just one definition. I think the definition which should be kept is Plg.

For the existence of Rhombus you could prove it forall A B, or forall A B C such that Cong A B B C.

For the unicity of Rhombus, you may use the tactics: smart_subst and treat_equalities which should automate some of the work.

I hope this helps.

Thank again for the contribution.

Julien

**Comment by ghost** [comment]
> We can not include it yet because there are open sections, so the file does not compile (see the travis logs). You need to close the section Rhombus_Existence_Unicity at the end of the file.

ok. i have see "travis". :+1: 

> It would be also better to move the additional lemmas about Plg out of the Rhombus file.
> We have everything in a quadrilateral file, but I may be worth spliting this file in differents parts.
> Charly is working on the generalization of some of Tarski's chapters to geometry of arbitrary dimension. You may also consider removing the 2D assumption in your proofs when it is possible. Our definition of Rhombus implies that it is a 2D figure, because the diagonals intersect, but we could have some charecterizations for which we need to assume it is 2D, for example that the four sides are congruent.

:+1: 

> For the existence of parallelograms, you already have the lemma:
plg_existence
I understand you did not find it, because we have two equivalent definitions of parallelogram in the library.... it should be merged to keep just one definition. I think the definition which should be kept is Plg.

ok i find plg_existence. 

Context: 2D geometry (absolute 2D Geometry ok)
```
plg_existence
     : forall A B C : Tpoint,
       A <> B -> exists D : Tpoint, Parallelogram A B C D
```

I prefere (parallelogram_existence) but when i modify my code PlgEx like this:

```
Require Export GeoCoq.Tarski_dev.Annexes.quadrilaterals.
Require Export GeoCoq.Tarski_dev.Annexes.quadrilaterals_inter_dec.
```
[...]
```
Lemma PlgEx: forall A B C, A <> B -> exists D, Plg A B C D.
Proof.
intros.
assert(exists D, Parallelogram A B C D).
apply plg_existence, H.
destruct H0.
exists x.
assert(Plg A B C x).
apply parallelogram_to_plg. <--- **ERROR because the context of parallelogram_to_plg 
                                             <--- is "Tarski_2D_euclidean"**
[...]
`Qed.`

Question: 
========
In Context Tarski_2D (not in Context Tarski_2D_euclidean, but in absolute euclidean):

"Lemma parallelogram_to_plg : forall A B C D, Parallelogram A B C D -> Plg A B C D."  ?

like...

"Theorem 11: The diagonals of a rhombus bisect each other, are
perpendicular, and bisect the angles of the rhombus." in Hyperbolic Geometry in the High School Geometry Classroom, Christi Donald, Iowa State University"

or in a non-euclidean tarski plan: 

"exists A B C D, Parallelogram A B C D /\ ~ Plg A B C D." ?

> For the existence of Rhombus you could prove it forall A B, or forall A B C such that Cong A B B C.

Currently, it is not obvious to me that, in the hyperbolic plane, only "if Cong A B B C then there is a point D such that Cong A D D C & B <> D & B in perp_bisectrice(A,C) & D in perp_bisectrice(A,C) & Midpoint M A C & Bet B,M,D" or something like that.

I search :-)

Thank you for your quick comments.
Roland

**Comment by jnarboux** [comment]
Yes I forgot that the two definitions for parallelograms are not equivalent in neutral geometry.....

To show the existence of a Rhombus you may use the following lemmas:

Lemma l10_2_existence_spec:
  forall Tn : Tarski_neutral_dimensionless,
  Tarski_neutral_dimensionless_with_decidable_point_equality Tn ->
  forall A B P : Tpoint, exists P' : Tpoint, ReflectL P' P A B

l10_2_existence:
  forall Tn : Tarski_neutral_dimensionless,
  Tarski_neutral_dimensionless_with_decidable_point_equality Tn ->
  forall A B P : Tpoint, exists P' : Tpoint, Reflect P' P A B

Cheers,

Julien

**Comment by jnarboux** [comment]
Thank you for the contribution.

**Pull request merged**
