### PR TITLE
Fix for math-comp/math-comp#270

### PR DESCRIPTION
**Pull request by pi8027**
This PR fixes the compilation of GeoCoq with math-comp/math-comp#270. CC: @CohenCyril @Boutry

### CODE REVIEW

**Comment by Boutry** [comment]
Thank you Kazuhiko!

**Comment by pi8027** [comment]
Since I thought this PR doesn't work with the current master branch of MathComp, I marked it as a draft. But CI didn't fail as I expected. This is weird...

**Comment by SkySkimmer** [comment]
It looks like travis doesn't compile enough, I can't see the modified `POF_to_Tarski.v` in the log.

Then as you expected it broke Coq's CI (last success https://gitlab.com/coq/coq/-/jobs/364817621 first failure https://gitlab.com/coq/coq/-/jobs/365078189, the only difference is the geocoq commit as the change between the coq commits is just test suite stuff)

**Comment by Boutry** [comment]
This is due to the fact that this file is not check by the CI (I thought we
had changed that). Thank you for spotting it.

https://github.com/GeoCoq/GeoCoq/blob/master/configure-ci.sh

Le sam. 30 nov. 2019 à 10:18, Gaëtan Gilbert <notifications@github.com> a
écrit :

**Comment by pi8027** [comment]
Maybe we should revert my commit to fix Coq's CI then put it back when math-comp/math-comp#270 is merged. Sorry for the inconvenience. cc: @ejgallego

**Comment by ejgallego** [comment]
Indeed, it seems we should wait until the math-comp PR has been merged, right?

Thanks @pi8027 !

**Comment by ejgallego** [comment]
It seems it is now time to merge this PR again, could you take care @pi8027 ?

**Comment by pi8027** [comment]
@ejgallego Yes.

**Pull request merged**
