### PR TITLE
Create SegmTrisect.v

### PR DESCRIPTION
**Pull request by ghost**
Trisection Segment

### CODE REVIEW

**Comment by maximedenes** [comment]
Doesn't this file contain unclosed sections? Where are the CI results?

**Comment by jnarboux** [comment]
Sorry Maxime I reverted the merge.

**Comment by maximedenes** [comment]
No worries! I can't find the CI results for this PR. Is there a configuration issue or were the results erased automatically after the PR was closed?

**Comment by jnarboux** [comment]
The CI results are here: https://travis-ci.org/GeoCoq/GeoCoq

In the past the CI results were displayed, I don't know why they are not
displayed in the pull request page anymore. I thought the results were
displayed only in case of failure, my mistake.

Julien

Le lun. 16 sept. 2019 à 13:16, Maxime Dénès <notifications@github.com> a
écrit :

**Comment by jnarboux** [comment]
Dear Roland,

I had a look at your file. You seems to have duplicated a lot of lemmas. For example the first three lemmas are just permutation of lemmas which are already available in GeoCoq. I would prefer not to duplicate so many lemmas. 
For example the use of lemma STl6_16_1b can be replaced by the use of the tactic ColR.
 Another example is : triangle_par_mid2 You don't need to introduce a new lemma, you can just use triangle_par_mid followed by tactics to deal with permutations: see Finish,  or perm_apply

Can you please simplify your code ?

Cheers,

Julien

**Comment by ghost** [comment]
ok, I'm refactoring the code.
Roland

**Pull request merged**
